### ISSUE TITLE
Compute ET statistics for each model type and regions

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-overview#13]
We have or will compute a standard monthly data product for each of the ET modeling efforts.  These data need to be summarized for each LandIQ level_2 type, and a number of regions in the delta.  A good start to this the EE script /ssj-delta-cu/ssj-overview/et_comparison.js  This script shows some some statistics for some of the models, for alfalfa, and showing the mean values.  This script need to be modified in the following ways:
- Include all the LandIQ level_2 sets.
- Update the code to include 
  *\* Upland and lowland regions
  *\* Later we may expand to counties
- Export the CSV files to a single Google Sheet

**Comment by andybell** [comment]
@qjhart Chart.image.byClass() can only work using a single value from one reducer. Combining multiple reducers in a single chart won't work. It's possible to have a separate chart for each of the stats we need but I think that it's going to get unruly really fast. 

I found a way to use a reduce by region to produce the stats for each of the ET results. The JSON output to the console is a bit hideous but I think that it has most of the info needed.  I'm at a bit of a loss about how to format the nested dictionaries into a csv.

**Comment by qjhart** [comment]
@andybell Okay.  I like your strategy.  

I think there are three ways forward,
-  Import these JSON files directly into the Google Spreadsheet, and then write some helper functions that allow us to parse the JSON, and reorganize as well see fit, and ready for graphing.  I've sent you an example sheet that does that.
- Same as above, but use Google Sheets JSON database engine to perform the tasks.  I forgot about that engine in my example above.
- Investigate the EarthEngine UI tools, which have recently been added to the system.
