### ISSUE TITLE
Results - relative difference and StdDev

### ISSUE THREAD

**Issue by andybell** [ssj-delta-cu/ssj-overview#14]
Started a script in EE to compare the different methods. Turns the ET images from the different methods into a imageCollection which can then be reduced to get the mean and standard deviation. 

The individual results can then be compared to the mean + std to get the relative difference and the zscore. 

See ssj-overview/et_compare_deviation.js for details.

**Comment by andybell** [comment]
@qjhart The bands for the eto method are in a different order than the other methods. Can you check that I've rearranged them correctly so that the months match? 

eto -b10, b11, b12, b1, ....
all the other methods - b1, b2, b3, ......

**Comment by qjhart** [comment]
@andybell My bad.  I should have made this more clear.  The eto method is not really a method at all.  It's just a good test to validate the other methods.  (It's the Potential ETo for a month, and doesn't change with commodity) It _SHOULD NOT_ be included in the calculation of the mean ET.
