### ISSUE TITLE
Figure 1 / Table 1

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-overview#15]
@andybell , @josue-medellin .  We need to start working on some of the additonal summary data for the report.   Figure 1 for the report is a summary of the Total amount of seasonal ET for each method for the the three regions.  In order to do this, we need another summary (the count) for each of our estimations.  This can be in the same graphs sheet, and please verify w/ @josue-medellin  that the figure and tables look okay.

ET_imc = Mean Daily ET for month (m) method (i) commodity (c)
M_m = Number of days in month (m)
n_c = number pixels in commodity  (c)

TAF_i = (mm to ft) \* ( Sum (over c) n_c \* (acres/pixel) \* Sum (over m) ET_imc \* M_m ) 

![image](https://cloud.githubusercontent.com/assets/344953/17496210/15a93fbe-5d71-11e6-817a-8d29a954de0b.png)

Table 1 is the same data, but in tablular form.

![image](https://cloud.githubusercontent.com/assets/344953/17496225/285f1db8-5d71-11e6-8535-732df9f2957b.png)

**Comment by andybell** [comment]
![image](https://cloud.githubusercontent.com/assets/7776675/17528106/ed004a1e-5e3b-11e6-84ed-5bad7a9fe3b4.png)

@josue-medellin here is an example of an graph for alfalfa in June
