### ISSUE TITLE
Figure 2 / Table 2 

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-overview#16]
@andybell / @josue-medellin , for Figures 2 ( one for each commodity).  We want to show the comparison of the mean values of the ET for each commodity for all the methods.

![image](https://cloud.githubusercontent.com/assets/344953/17496470/5e4964a0-5d72-11e6-8e6b-7f56c7e3d623.png)

Again, we want to show the same data as a table, There will be one table per commodity.  the columns of the commodity are each method.

![image](https://cloud.githubusercontent.com/assets/344953/17496496/775ec2fa-5d72-11e6-8982-5583a927b420.png)

**Comment by andybell** [comment]
![image](https://cloud.githubusercontent.com/assets/7776675/17528345/1c8829cc-5e3d-11e6-9f14-249dcf14e598.png)

@josue-medellin Example for alfalfa. Let me know what you want changed.

**Comment by josue-medellin** [comment]
We would like units in the y axis, these should be mm/day. I would also like to have the ability to change the model labels. e.g. CalSIMETAW, UCD-PT, DisALEXI, ITRC, METRIC-UCD, NASA-ARC, DETAW.

**Comment by andybell** [comment]
![image](https://cloud.githubusercontent.com/assets/7776675/17529024/b5a2a98c-5e3f-11e6-9525-17426065d4d7.png)

**Comment by josue-medellin** [comment]
This looks OK. Let's do it for all available land use classes. Enlarge fonts for Y axis legend please. thanks, jma

**Comment by josue-medellin** [comment]
Figures have been generated. Thank you. I will have William Li to generate the Tables for Alfalfa, Corn and Pasture.

**Comment by qjhart** [comment]
Either you need to divide by 10, or make the Units (tenths mm / day)

**Comment by andybell** [comment]
Let's change the units on the graphs

**Comment by josue-medellin** [comment]
Do we need to redo all graphs then?
