### ISSUE TITLE
Crop land use classes

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#17]
@andybell please prepare a map for the Land IQ land use classes in level 2. That will be the replacement over the shared version of the draft figure 1. Also, prepare a table with land use, surface area (acres), and percentage of total Delta area.  All land use classes within the Delta should sum up to about 737 thousand acres. Thanks.

**Comment by andybell** [comment]
| Commodity | Number | square meters | acres | percent |
| --- | --- | --- | --- | --- |
| Corn | 23 | 371,639,640.45 | 91834 | 13.55 |
| Alfalfa | 1 | 324,557,286.47 | 80200 | 11.84 |
| Urban | 2006 | 251,575,014.03 | 62165 | 9.17 |
| Water | 2007 | 243,625,266.29 | 60201 | 8.88 |
| Upland Herbaceous | 2005 | 219,926,302.65 | 54345 | 8.02 |
| Turf | 916 | 210,266,159.26 | 51958 | 7.67 |
| Semi-agricultural/ROW | 913 | 196,424,489.15 | 48537 | 7.16 |
| Pasture | 800 | 194,501,085.79 | 48062 | 7.09 |
| Vineyards | 109 | 149,454,553.33 | 36931 | 5.45 |
| Tomatoes | 278 | 146,873,058.71 | 36293 | 5.36 |
| Wet herbaceous/sub irrigated pasture | 2008 | 101,003,516.45 | 24958 | 3.68 |
| Riparian | 2004 | 87,362,536.15 | 21588 | 3.19 |
| Truck Crops | 279 | 38,638,966.47 | 9548 | 1.41 |
| Other Deciduous | 914 | 31,218,602.10 | 7714 | 1.14 |
| Rice | 24 | 30,908,149.83 | 7638 | 1.13 |
| Pears | 412 | 24,067,372.14 | 5947 | 0.88 |
| Almonds | 500 | 21,078,376.53 | 5209 | 0.77 |
| Forage Grass | 2003 | 18,234,577.85 | 4506 | 0.66 |
| Potatoes | 246 | 16,769,775.09 | 4144 | 0.61 |
| Cucurbit | 277 | 15,874,194.18 | 3923 | 0.58 |
| Floating Vegetation | 2002 | 14,401,398.85 | 3559 | 0.53 |
| Walnuts | 503 | 14,065,944.59 | 3476 | 0.51 |
| Cherries | 403 | 8,372,867.16 | 2069 | 0.31 |
| Olives | 409 | 5,870,075.29 | 1451 | 0.21 |
| Bush Berries | 108 | 4,799,238.50 | 1186 | 0.18 |
| Pistachios | 502 | 598,946.00 | 148 | 0.02 |
| Citrus | 425 | 33,138.29 | 8 | 0.00 |

The sum of all the land classes above is 677,597 acres. Is that reasonable?

**Comment by josue-medellin** [comment]
Legal delta area. is 737 thousand acres. Would you please verify the original LU boundaries adds up to that, if so then we are good. My understanding is that the LU company (land iq) accounted for buffer areas in the fields. so perhaps having less acreages in the field edges is due to that.

**Comment by andybell** [comment]
Difference between legal delta and land use is because "delta" is clipped to DETAW region. 

![image](https://cloud.githubusercontent.com/assets/7776675/17533586/7232f8be-5e53-11e6-86e2-c6567a1fc51a.png)

**Comment by josue-medellin** [comment]
Thanks much. Please dont forget to mark the highlands and lowlands boundaries in the Delta.

**Comment by andybell** [comment]
I tabulated the areas for the full legal delta in earth engine and got similar numbers. But by tabulating in ArcGIS the number for fallow, sunflow, safflower get closer to the total.

| Crop | Acres |
| --- | --- |
| FALLOW | 54024.86268 |
| SAFFLOWER | 5921.698352 |
| SUNFLOWER | 583.6372995 |
