### ISSUE TITLE
Chart for Kc

### ISSUE THREAD

**Issue by andybell** [ssj-delta-cu/ssj-overview#20]
Here is an example chart looking at Kc for the different methods for all of the landuse classes for the month of July. 

`Kc = Mean ET for method / ETO  for each of the landuse categories`

![image 1](https://cloud.githubusercontent.com/assets/7776675/18054482/1571976e-6dd2-11e6-9a93-f40a8608a8d5.png)

**Comment by josue-medellin** [comment]
Please add may and september and follow Quinn's suggestions

**Comment by qjhart** [comment]
@andybell .  My comments:
- [ ] order X axis by mean Kc from low to high
- [ ] We may have to identify if some of the methods don't work for some veg types.

**Comment by andybell** [comment]
# May

![kc_may](https://cloud.githubusercontent.com/assets/7776675/18142852/603a13a4-6f8d-11e6-9ce2-66f7f6745801.png)

# July

![kc_july](https://cloud.githubusercontent.com/assets/7776675/18142850/602ee1aa-6f8d-11e6-90e0-d6034cf142a3.png)

# September

![kc_sept](https://cloud.githubusercontent.com/assets/7776675/18142851/60375d94-6f8d-11e6-9153-6d3fb57dec73.png)
