### ISSUE TITLE
monthly ET estimates at stations

### ISSUE THREAD

**Issue by andybell** [ssj-delta-cu/ssj-overview#22]
For each month, extract the estimated ET for the five stations (D1, D2, D3, D4, D5) in the Delta for each method.

**Comment by andybell** [comment]
Example output for UCD-Metric:

Station D1 = 1
Station D2 = 2
Station D3= 3
Station D4 =4
Station D5 = 5

![ee-chart](https://cloud.githubusercontent.com/assets/7776675/18287189/0d6c6346-7444-11e6-8c54-31e95f8c69a4.png)

| Property | 2 | 1 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- | --- |
| 1_OCT | 12 | 10 | 16 | 18 | 29 |
| 2_NOV | 5 | 5 | 8 | 9 | 14 |
| 3_DEC | 8 | 8 | 12 | 12 | 10 |
| 4_JAN | 7 | 8 | 11 | 12 | 10 |
| 5_FEB | 9 | 13 | 11 | 20 | 22 |
| 6_MAR | 19 | 29 | 34 | 43 | 43 |
| 7_APR | 19 | 27 | 53 | 63 | 44 |
| 8_MAY | 14 | 11 | 59 | 66 | 23 |
| 9_JUN | 35 | 23 | 49 | 42 | 26 |
| a_JUL | 51 | 34 | 26 | 17 | 26 |
| b_AUG | 45 | 30 | 8 | 21 | 16 |
| c_SEP | 24 | 15 | 16 | 25 | 18 |

**Comment by josue-medellin** [comment]
Andy, would you please remind me which issue is this? Is this CIMIS stations?

**Comment by andybell** [comment]
@josue-medellin I'm not totally sure. Quinn forwarded an email from Eric Kent with coordinates for some stations.

**Comment by andybell** [comment]
Compare all methods in September since that's when actual bare soil measurements where taken. Waiting for actual measurements.

**Comment by josue-medellin** [comment]
@qjhart Quinn, what are we comparing these to? Appendix A from KT? Do we have a table from Kent with Daily ET Values?

**Comment by andybell** [comment]
@josue-medellin here are some charts for each of the stations comparing the mean daily ET for September from each of the methods with the average daily ET measured at the station. Stations D3 & D4 are outside the legal delta bounds which is why there is some missing data. 

![image 1](https://cloud.githubusercontent.com/assets/7776675/18358059/568b8358-75c1-11e6-982d-94b91705ef12.png)

![image 2](https://cloud.githubusercontent.com/assets/7776675/18358068/5eb45cee-75c1-11e6-88c4-6714604214ce.png)

![image 3](https://cloud.githubusercontent.com/assets/7776675/18358075/643ca5c2-75c1-11e6-80d7-ab2bc0cc90bd.png)

![image 4](https://cloud.githubusercontent.com/assets/7776675/18358079/6713ef4e-75c1-11e6-913d-2b8efe08ffe8.png)

![image 5](https://cloud.githubusercontent.com/assets/7776675/18358085/6d6d2ff4-75c1-11e6-8885-258a7e2edb31.png)

**Comment by qjhart** [comment]
@andybell What I would do is run the measured value as a big horizontal bar across the other points, so we can see where they line up, against the satelite estimates.

**Comment by andybell** [comment]
![d1](https://cloud.githubusercontent.com/assets/7776675/18439668/4601c6da-78d4-11e6-992b-3c6d1fa6737b.png)
![d2](https://cloud.githubusercontent.com/assets/7776675/18439670/46074ab0-78d4-11e6-9587-63fdd5970c85.png)
![d3](https://cloud.githubusercontent.com/assets/7776675/18439666/46011fa0-78d4-11e6-9ec9-c2053755f10c.png)
![d4](https://cloud.githubusercontent.com/assets/7776675/18439667/4601a11e-78d4-11e6-9384-fed4ba215bbd.png)
![d5](https://cloud.githubusercontent.com/assets/7776675/18439669/4603073e-78d4-11e6-90c6-3cc51188a221.png)

**Comment by josue-medellin** [comment]
Andy why we have no PT on D1 and D2?

**Comment by andybell** [comment]
PT had values of zero for the month of Sept at those two locations. I removed all zero values from the above charts. 

Here is a screenshot. The sampling sites are the two small dots. All the areas with ET=0 are shown in the darker gray 

![image](https://cloud.githubusercontent.com/assets/7776675/18440456/32d1735a-78d7-11e6-81cb-c2544823c4ad.png)

**Comment by ghost** [comment]
UCD-PT method overestimated/failed to generate ET in September for following reasons:
1. Landsat images in September is cloudy. Landsat images in late August is also somewhat cloudy.  In addition, Images after Sep, 2015 were not processed and included in the interpolation. Therefore, there may not be enough data for interpolation at some pixel to generate daily ET in September.
2. The Kc interpolation method I coded had some design flaws. At some pixel, ET from UCD-PT at Landsat overpass date on August 12 is lower than August 28. If September data is not available, by extrapolation from two points in August, ET in September maybe continually increase. I have yet to check with Kc value in those day to confirm the problem. For Phase II, Quinn's METRIC Kc interpolation script will be used to estimate daily ET. This, in addition to standardize data protocol at phase II,  will most likely solve the issue. I will develop a different approach with Yufang to estimate ET at non-Landsat overpass date by incorporating and down scaling data from other satellites. Hopefully, the approach will be ready by the end of phase II.
