### ISSUE TITLE
DisAlexi sending new estimates

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#23]
USDA-ARS is sending new estimates due to an error. @qjhart Do we have an streamlined process for updating their estimates? Thanks, Josue

**Comment by qjhart** [comment]
Issue moved to [ssj-delta-cu/ssj-disalexi #2](https://github.com/ssj-delta-cu/ssj-disalexi/issues/2) via [**ZenHub**](https://www.zenhub.com/)
