### ISSUE TITLE
Endnote references and add a reference.

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#28]
William please update my Endnote library with the study reference. Also add this one. 

http://escholarship.org/uc/item/3t82s21b# the endnote record is in the literature folder. 

https://drive.google.com/a/ucdavis.edu/file/d/0B7Ahz0szB4ZManN5QmV2allaR2s/view?usp=sharing

Kind regards,

Josue

**Comment by josue-medellin** [comment]
@koolwill are we done with this ?

**Comment by koolwill** [comment]
@josue-medellin Yes, the updated files are in Google Drive.
