### ISSUE TITLE
DisALEXI found error in code.

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#30]
@qjhart @andybell @koolwill 

We received new estimates from USDA after they found an error in the imagery they employed. If i understand the flow correctly.  Quinn will upload, Andy will grab from Earthengine into spreadsheets and william will redo all charts when is available. I realize this is short notice. So ETA is Tuesday from Quinn, perhaps a little earlier, and Andy would have until Wednesday to put into spreadsheets. I guess a new map for Disalexi will be pending for the new cute panel with all methods. Than you all and sorry for pushing the emergency button once again.

**Comment by andybell** [comment]
Figures in report that will have to be updated with the new data 
- [x] Figure ES-1 - evapotranspiration estimate for entire year
- [x] Figure 4? - bare soil evapotranspiration - this one is not in the spreadsheet. Need to check if the numbers from et_comparisons_fieldpoints.js actually change and then export to csv to redo graphs in R
- [x] Figure 5 - should be the same as figure ES-1
- [x] Table 3 - totals for DSA and legal delta 
- [x] Figure 6 - all of the 8 crops figures should be redone 
- [x] Figure 7 - all need to be redone with the new data
- [x] Figure 8 - redo for DISALEXI only

**Comment by josue-medellin** [comment]
@andybell @koolwill  Is William doing this already?

**Comment by andybell** [comment]
@josue-medellin I'm still waiting on the asset to be shared with my account (see https://github.com/ssj-delta-cu/ssj-disalexi/issues/2). I'll let @koolwill know when the updated data is added to the google sheet.

**Comment by josue-medellin** [comment]
@qjhart @andybell @koolwill  apparently thing is done but perhps still needs to be uploaded.

**Comment by josue-medellin** [comment]
@andybell I've been told asset is loaded now with access granted

**Comment by andybell** [comment]
@koolwill Google sheets is updated. I've already addressed a couple of the figures that needed to be updated (see checklist above). Can you be in charge of updating the rest?

**Comment by koolwill** [comment]
@andybell Yes, I can update the rest.

**Comment by josue-medellin** [comment]
@andybell @koolwill Andy, are the Kc figures updated? if so, would you please resend issue? I still need to put in that section

**Comment by andybell** [comment]
@josue-medellin Kc figures will need to be updated as well - I was going off the current list of figures in the draft. Can you put a placeholder in the document where you want the figures to go?

**Comment by josue-medellin** [comment]
Andy please look at the comment in document, it will be right before island estimates. thanks

**Comment by josue-medellin** [comment]
Are we all done with the DisALEXI changes @andybell and @koolwill ?

**Comment by andybell** [comment]
@josue-medellin Almost - I just realized that we should redo fig 9 + 10 which is the estimates for the island subregions.

**Comment by andybell** [comment]
This can be closed. All figures in the draft have been updated to the new results.

**Comment by josue-medellin** [comment]
Nice job. Thank you all.
