### ISSUE TITLE
Land Use Classes and Totals

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#32]
We need to double check LU classes and totals. Table 1 of land use and numbers in text. Summation in table 1 does not work.

Alfalfa\*    80,201
Almonds\*    5,210
Bush Berries\*   1,186
Cherries\*   2,069
Citrus\* 8
Corn\*   91,833
Cucurbit\*   3,923
Olives\* 1,451
Other Deciduous\*    7,713
Pasture\*    48,062
Pears\*  5,947
Pistachios\* 148
Potatoes\*   4,144
Rice\*   7,637
Semi-agricultural/ROW(?)\*   48,523
Tomatoes\*   36,290
Truck Crops\*    9,547
Turf\*   2,175
Upland Herbaceous\*  54,344
Vineyards\*  36,930
Walnuts\*    3,474
Total Irrigated Acres   450,815

**Comment by josue-medellin** [comment]
@qjhart @andybell @nickrsan @jrmerz Good morning, who can help me follow up on this? Will it be Nick Justin, Quinn or others?

**Comment by nickrsan** [comment]
Hi Josue,
As of now, I'm overbooked until next month when I can start coming online with this project in earnest. Still trying to get up to speed to understand METRIC, etc so I can be of more assistance here. Also, @andybell is out for at least another week for his honeymoon, so can't help in the immediate term, at least.

**Comment by josue-medellin** [comment]
Understood. @qjhart @jrmerz ? Let me know how can I access this in google earth engine to crosscheck.  Kind regards, Josue

**Comment by jrmerz** [comment]
@josue-medellin I'm happy to help, but I come with startup cost :(  I have a 45min introduction to the current Earth Engine code base, mostly in regards to the ERDAS work Nadya is doing.  So I will need to be brought up to speed.

As for sharing the code, I only have writer permission, it doesn't let me share it.  Looks like @qjhart has to do that.

**Comment by nickrsan** [comment]
@josue-medellin Just to add to what Justin's saying, I have a similar time-cost on starting up should I work on this project at any point. I'm pretty familiar with Earth Engine itself (but not the extensive experience that Quinn and Andy have still), but I'll definitely be slow on any work until up to speed.

I'm also running into a similar issue as Justin mentioned about permissions - working to resolve that in another ticket.

**Comment by josue-medellin** [comment]
@qjhart please unlock the appropriate permits. @jrmerz I dont need to access code myself just be able to recreate tables or see underlying calculations.

**Comment by qjhart** [comment]
@josue-medellin here are statistics directly from the landuse dataset:  I'll give them by level_1 and level_2. 
First the total acres (according to landuse) = 752171 acres.  This is the total reported from land IQ.  Of that we have: 

| level_1 | acres |
| --- | --- |
| Citrus/Subtropical | 1590 |
| Field Crops | 102004 |
| Idle | 55260 |
| Native | 91475 |
| Native Riparian | 27898 |
| Other Deciduous | 26105 |
| Pasture | 143834 |
| Rice | 8302 |
| Semi-agricultural | 52161 |
| Truck Crops | 57564 |
| Urban | 83583 |
| Vineyards | 38608 |
| Water | 63786 |

| level_1 | level_2 | acres |
| --- | --- | --- |
| Pasture | Alfalfa | 81051 |
| Other Deciduous | Almonds | 5798 |
| Truck Crops | Bush Berries | 1198 |
| Other Deciduous | Cherries | 2090 |
| Citrus/Subtropical | Citrus | 8 |
| Field Crops | Corn | 95355 |
| Truck Crops | Cucurbit | 4200 |
| Idle | Fallow | 55260 |
| Native Riparian | Floating Vegetation | 3585 |
| Pasture | Forage Grass | 6562 |
| Citrus/Subtropical | Olives | 1582 |
| Other Deciduous | Other Deciduous | 8450 |
| Pasture | Pasture | 54061 |
| Other Deciduous | Pears | 5950 |
| Other Deciduous | Pistachios | 150 |
| Truck Crops | Potatoes | 4115 |
| Rice | Rice | 8302 |
| Native Riparian | Riparian | 24313 |
| Field Crops | Safflower | 5922 |
| Semi-agricultural | Semi-agricultural/ROW | 52161 |
| Field Crops | Sunflower | 728 |
| Truck Crops | Tomatoes | 37744 |
| Truck Crops | Truck Crops | 10308 |
| Pasture | Turf | 2160 |
| Native | Upland Herbaceous | 62934 |
| Urban | Urban | 83583 |
| Vineyards | Vineyards | 38608 |
| Other Deciduous | Walnuts | 3667 |
| Water | Water | 63786 |
| Native | Wet herbaceous/sub irrigated pasture | 28541 |

**Comment by josue-medellin** [comment]
@koolwill take a look at this versus text and comments

**Comment by koolwill** [comment]
@josue-medellin Just to be clear, do you want me to update table 1 with these new values?

**Comment by josue-medellin** [comment]
Yes. Also check areas in paragraph. write comments when is not clear. thanks. josue

**Comment by koolwill** [comment]
@josue-medellin I've added changes to table 1 and comments in the draft.

**Comment by josue-medellin** [comment]
we are using the word document

**Comment by andybell** [comment]
Two thoughts about this: 
1. The counts in the table above from Land IQ are not limited to the Delta Service Area. The landuse raster has a slightly larger extent than the service area.
2. The counts for the landuse that were done in EE for the DSA and subregions (https://code.earthengine.google.com/f6458c5ccfab0136886af671a4464245) were calculated using a reducer. Maybe this added some error to the sums?

**Comment by josue-medellin** [comment]
@andybell We are reporting two levels. DSA and legal Delta, I am assuming that withe the exception of the DETAW and CalSIMETAW all methods report for the Legal Delta using Land IQ database. Please help me fix inconsistencies in the word document tables and the overall calculation. I'll share the main report document in an email. THis is an important issue to correct.

**Comment by josue-medellin** [comment]
@andybell did you check Quinn calculations above? @qjhart Help us on this please.

**Comment by josue-medellin** [comment]
@andybell Andy, would you please produce a Level 1 and level 2 summaries for: 1) Full LU survey extent 2) Legal Delta,  and 3) Delta Service Area? If we have a map with boundaries would be a plus, otherwise I can use Figure 1. Thnaks,
