### ISSUE TITLE
Land use classes Delta Service Area Chart ET per unit area

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#33]
Check for DSA Chart by DETAW areas. much lower

**Comment by josue-medellin** [comment]
@qjhart @jrmerz I need to check why the DSA reports much lower per unit area estimates. Please provide link to check what goes into calculations.

**Comment by qjhart** [comment]
Redid the calculations, in https://docs.google.com/spreadsheets/d/183ksTSkO04K4WuIjI7Q2oxxmvbJswxVjTOXPlMBQKAk/edit?usp=sharing and sent notice.  If these look good, please close.

**Comment by josue-medellin** [comment]
Quinn, thanks. These look much better. How can I  get totals by 'island' to redo the graph on report.

**Comment by qjhart** [comment]
@josue-medellin I was expecting the islands were correct, so I didn't redo those.  Those are in the spreadsheet, I think you were accessing last nite.

**Comment by josue-medellin** [comment]
Sounds perfect thanks very much. I will have that worked out. no problem.

Kind regards,

Josue

**Comment by josue-medellin** [comment]
@andybell Andy, lets redo this charts.

**Comment by andybell** [comment]
@josue-medellin @qjhart It looks like it just was the total area that was wrong for the DSA. Let me know if I'm misunderstanding this issue about what got recalculated. Prior versions of the chart might have used the area of the bounding box.  

Here is an updated chart of the islands using an area of 679,000 acres to normalize the entire service area. 

![dsa_subregion_acre-feet_by_island_area](https://cloud.githubusercontent.com/assets/7776675/18847146/1e4727a6-83f7-11e6-8774-021d7e0f591c.png)

**Comment by josue-medellin** [comment]
@andybell,  do all areas include **just crop classes** OR **ALL** LU classes? if the fist, we are good to go I think. If second, @qjhart should we use just crops and redo?

**Comment by andybell** [comment]
@josue-medellin The figure only contains the data from the crop classes (using the include=yes list from the Crops spreadsheet tab).

**Comment by josue-medellin** [comment]
Then I'll close the issue. We should be good to go with this. Thank you.

**Comment by josue-medellin** [comment]
@andybell , please send boundaries DSA and Legal Delta to Forrest. 
@fmelton we are investigating that but is not part of this thread, look at issue #36

**Comment by andybell** [comment]
DSA -
https://github.com/ssj-delta-cu/ssj-overview/blob/master/detaw_subareas.geojson

Legal Delta -
https://fusiontables.google.com/DataSource?docid=1pwTPCh-j_aDA2MUbk12LxorHFrW-DnEgYqqySPk5#map:id=3
