### ISSUE TITLE
Table 3 and Figure 5 (and ES-1) bug after expanding DSA or ROI boundaries.

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#36]
@andybell Table 3 estimate and Figure 5 in the report seem to have a bug for SIMS and possibly other methods in reporting DSA and Legal Delta. Please check. We need to determine what is actually included in the estimations out of DSA. Are we using the Figure 4 blue rectangle (ROI) or are we using something else. legal delta should be around 737 thousand acres.

**Comment by andybell** [comment]
@josue-medellin can you expand with some more detail about what is wrong? Is it that the estimate in table 3 is higher for the DSA than the legal delta?

It looks like SIMS was clipped to the delta service bounds - so it might not be valid to report estimates for the legal delta for the SIMS method (similar to CalSIMETAW & DETAW). 

Red polygon is the legal delta bounds. Note - the area in the upper middle with data that is outside the bounds. That is included in the DSA total but not legal delta.

![image](https://cloud.githubusercontent.com/assets/7776675/18847733/4ca8350c-83f9-11e6-931e-e8e4348464dc.png)

**Comment by josue-medellin** [comment]
I see the problems. So do we have LU from Land IQ for all DSA and all the Legal Delta?

**Comment by andybell** [comment]
Landuse from Land IQ covers the entire extent of the DSA. 

There are two spots where the legal delta does not have land use:

The mouth of delta - by Pittsburg: 

![image](https://cloud.githubusercontent.com/assets/7776675/18848627/3e533a16-83fd-11e6-80bd-eeec19977490.png)

Near the Stanislaus on the eastern border

![image](https://cloud.githubusercontent.com/assets/7776675/18848602/238d9726-83fd-11e6-9294-fff478648180.png)

**Comment by andybell** [comment]
Just to be clear though - I think that the issue with SIMS is not related to the LAND IQ data. It's that the monthly ET rasters don't have any data outside the DSA boundary.

**Comment by josue-medellin** [comment]
@andybell it seems to me we should be reporting DSA as more than two methods did not calculated for areas other than the DSA.  I will open an issue on that to update some information.
@qjhart @fmelton this is just for your information. I will see the best way of updating the report without too much pain. We will probably require all groups next time to calculate Legal Delta as it is in the interest of the Delta Stakeholders. I'll mention that in the caveats.
