### ISSUE TITLE
Remove some values from Kc Charts

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#37]
@andybell please remove the purple dots for the floating veg, riparian, water, wetland herbaceous, upland herbaceous and urban classes, since SIMS does not currently provide estimates for these regions.

**Comment by andybell** [comment]
![kc_may_exclude_sims_natclasses](https://cloud.githubusercontent.com/assets/7776675/18836219/ff459452-83cc-11e6-93e9-6f6a8f980028.png)
![kc_july_exclude_sims_natclasses](https://cloud.githubusercontent.com/assets/7776675/18836221/017f2fe4-83cd-11e6-9ca5-af01f15932a9.png)
![kc_september_exclude_sims_natclasses](https://cloud.githubusercontent.com/assets/7776675/18836223/03236482-83cd-11e6-8d6a-b4114685cf84.png)
<img width="708" alt="kc_legend" src="https://cloud.githubusercontent.com/assets/7776675/18836229/06483d86-83cd-11e6-8f62-79d179f9013b.png">

Natural/Native landuse catagories list above removed for SIMS. Figures in report should be updated with these new charts @koolwill.

**Comment by josue-medellin** [comment]
@andybell I was thinking to remove all that is not included in the crop ET calculation except for fallow land to avoid some noise. @koolwill I am updating these charts in the main report but not in the Appendix. So please update appendix once this last request is completed.

**Comment by andybell** [comment]
New charts - only showing the crop catagories that are included in the ET calculations. The order of the crops on the x-axis are sorted from high Kc (average of all methods) to low Kc using the estimates from July. 

![kc_et_crops_only_july](https://cloud.githubusercontent.com/assets/7776675/18838442/7ee0be6e-83d5-11e6-9483-c911ab495803.png)
![kc_et_crops_only_may](https://cloud.githubusercontent.com/assets/7776675/18838443/7ee0f460-83d5-11e6-9173-abe2fd66264a.png)
![kc_et_crops_only_sept](https://cloud.githubusercontent.com/assets/7776675/18838444/7ef3db02-83d5-11e6-9b93-d82014286ff8.png)

**Comment by josue-medellin** [comment]
Great this we will use. Lets close.
