### ISSUE TITLE
Overview Map needs update

### ISSUE THREAD

**Issue by ghost** [ssj-delta-cu/ssj-overview#7]
The Existing CIMIS Stations links and locations at our overview map are outdated. Take Twitchell Island (140) for example, it is no longer active while a new station, Hastings Tract East (212), was added in 2009. I made a shapefile of all CA CIMIS stations as of May 2015. Please contact me if it is useful.

**Comment by josue-medellin** [comment]
Who should we assign this to?

**Comment by qjhart** [comment]
Eric is supposed to update the locations of the new CIMIS stations, and the field data.

**Comment by josue-medellin** [comment]
Can we close this one?
