### ISSUE TITLE
Results Updates

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-overview#9]
@NadyaAlexander @josue-medellin I have added in the template for the results.  
- [x]  We need to assign someone to choose the regions that we are going to use, and the crops we will review.  RIght now we only have the DSA.
- [x] [Results](https://github.com/ssj-delta-cu/ssj-overview/blob/master/results/README.md#results-model) Right now , we only have two required results.  monthly.csv and month/ET.tif.  Do we need to add some additional ones?

**Comment by NadyaAlexander** [comment]
@qjhart @josue-medellin Since Yufang and I are lead on the modeling group coordination / report writing, we should probably draft the regions and crop groups? We will need the LandIQ data to do a crosswalk for the LandIQ - DWR and we should also broaden the results to include water and natural vegetation. Do you think the regions should have coordination from the DWM office to line up with some of their reporting, or should we base it more on CIMIS / microclimates / geography?

**Comment by NadyaAlexander** [comment]
I think we might wait until we have the inputs / intermediate outputs tables filled in from the modelers before we ask for additional required results? I am a little unclear still on how much Jay wants to define before we send out the draft protocols and how much we will add after we get input.

**Comment by josue-medellin** [comment]
@NadyaAlexander on your first comment. We have an islands layer I think. Yes on Land IQ for cross walk to DWR plus water and natural vegetation. I dont think we will get newer data from DWM office on islands layer. Second comment. I was under the impression we were providing a draft of what we think their models provide to pre-populate their tables and then let them comment if we are right or wrong.

**Comment by NadyaAlexander** [comment]
@josue-medellin I think Quinn put the table on Github, but I'm waiting to hear back on that. I think Github would be a natural place for it to be centrally available. I wasn't thinking so much about layer data from the DWM office, it was more that there are a lot of small islands and waterways, and I wasn't sure if there were management groupings currently in place that we might want to line up our boundaries with (for example - even if we are summarizing at a scale sub to "North Delta", etc., we might want our boundaries to line up with the edge of that region)

**Comment by qjhart** [comment]
@ssj-delta-cu/ssj, the individual projects have been created and teams have been made.  We can discuss what other GitHUB support is required, but otherwise I think this is complete

I'm pretty sure the Land IQ is the DWR crop groups, what we will need is the CDL -to DWR crop groups which have been done alreasy, but Nadya and I might not agree on the results.
